# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gra',
            old_name='nazwa_gryy',
            new_name='nazwa_gry',
        ),
        migrations.RenameField(
            model_name='paczkagier',
            old_name='wydawca',
            new_name='kreator_paczki',
        ),
        migrations.RenameField(
            model_name='paczkagier',
            old_name='logo_gry',
            new_name='logo_paczki',
        ),
    ]
