# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170606_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='gra',
            name='jest_ulubiona',
            field=models.BooleanField(default=False),
        ),
    ]
