# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gra_jest_ulubiona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paczkagier',
            name='logo_paczki',
            field=models.FileField(upload_to=''),
        ),
    ]
